version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
        - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgnetwork

volumes:
  pgdata:

networks:
  pgnetwork:
    driver: bridge
